### ISSUE TITLE
Investigate Deepcode.ai integration

### ISSUE THREAD

**Issue by Laracodacy** [codacy/coverage-parser#61]
Deepcode reached out to us to partner with Codacy - request and information bellow:
https://docs.google.com/document/d/18BlMgC7tBBnkHkwDoS28j4kivrk1oAOgN8aEzej47f0/edit?ts=5e6fbe9c#heading=h.jm8dn3v1ylny

The goal of this task is too investigate if this would work with our Client side tools system and add details to the document above.

**Comment by franciscodua** [comment]
It's technically feasible to integrate with Deepcode.ai.

But it will be far easier when client-side tools are more dynamic (in the sense that users can register their own client-side tools)
